### ISSUE TITLE
RuntimeError: runtime_error:  arg <= 0

### ISSUE THREAD

**Issue by tiboloic** [comorment/mixer#25]
I am trying to run mixer on the height GWAS ldsc file provided by Neale's lab, for testing my install of mixer.
I get the following error message:
```
***********************************************************************
* mixer.py: Univariate and Bivariate Causal Mixture for GWAS
* Version 1.2.0
* (c) 2016-2020 Oleksandr Frei, Alexey A. Shadrin, Dominic Holland
* Norwegian Centre for Mental Disorders Research / University of Oslo
* Center for Multimodal Imaging and Genetics / UCSD
* GNU General Public License v3
***********************************************************************
Call: 
./mixer.py fit1 \
	--out ../mixer/50.mixer \
	--bim-file /REF/ldsc/1000G_EUR_Phase3_plink/1000G.EUR.QC.@.bim \
	--ld-file /REF/ldsc/1000G_EUR_Phase3_plink/1000G.EUR.QC.@.run4.ld \
	--trait1-file ../strat/sumstats_ungz/50_irnt.ldsc.imputed_v3.both_sexes.tsv \
	--extract /REF/ldsc/1000G_EUR_Phase3_plink/1000G.EUR.QC.prune_maf0p05_rand2M_r2p8..snps \
	--threads 16 
)
INFO:root:__init__(lib_name=libbgmg.so, context_id=0)
Traceback (most recent call last):
  File "/tools/mixer/precimed/mixer.py", line 23, in <module>
    args.func(args)
  File "/tools/mixer/precimed/mixer/cli.py", line 647, in execute_fit1_or_test1_parser
    results = init_results_struct(libbgmg, args)
  File "/tools/mixer/precimed/mixer/cli.py", line 639, in init_results_struct
    results['options']['sum_weights'] = float(np.sum(libbgmg.weights))
  File "/tools/mixer/precimed/mixer/libbgmg.py", line 168, in weights
    return self._get_vec_impl(self.cdll.bgmg_retrieve_weights, np.float32, self.num_tag, trait=None)
  File "/tools/mixer/precimed/mixer/libbgmg.py", line 410, in _get_vec_impl
    self._check_error(func(*args))
  File "/tools/mixer/precimed/mixer/libbgmg.py", line 418, in _check_error
    raise RuntimeError(self.get_last_error())
RuntimeError: runtime_error:  arg <= 0
```

**Comment by tiboloic** [comment]
Apologies for the trivial report. I found out that the file provided to `--extract` did not exist
